### ISSUE TITLE
PhoneGap Build Error

### ISSUE THREAD

**Issue by Ralpharoo** [bitstadium/HockeySDK-Cordova#85]
I am having trouble building with PhoneGap Build. This was working fine <12 hours ago but now fails with this error;

`Failed to install 'cordova-plugin-hockeyapp': CordovaError: Uh oh!
"/project/cordova/plugins/cordova-plugin-hockeyapp/src/android/HockeySDK-Android/HockeySDK-5.0.1.aar" not found!
    at copyFile (/project/cordova/lib/pluginHandlers.js:219:36)
    at install (/project/cordova/lib/pluginHandlers.js:74:13)
    at Object.process (/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /project/cordova/Api.js:254:18
    at _fulfilled (/project/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:816:13)
    at /project/cordova/node_modules/q/q.js:570:49
Uh oh!
"/project/cordova/plugins/cordova-plugin-hockeyapp/src/android/HockeySDK-Android/HockeySDK-5.0.1.aar" not found!`

I can see you are updating things so it may need some time to all sync through. Thought you may want to know just in case.

Love this plugin by the way. Thanks!

**Comment by Ralpharoo** [comment]
Looks like the plugix.xml needs to be updated inline with the new SDK version;

`<resource-file src="src/android/HockeySDK-Android/HockeySDK-5.0.1.aar" target="libs/HockeySDK-5.0.1.aar" />`

to 

`<resource-file src="src/android/HockeySDK-Android/HockeySDK-5.0.1.aar" target="libs/HockeySDK-5.0.2.aar" />`

**Comment by xtarx** [comment]
I am having the same issue as well

**Comment by TroubleMakerBen** [comment]
Hey people,

I just released 5.0.1 of the plugin that references the correct version of the underlying native Android SDK. I apologize for this oversight on my side.

Let me know if the release fixes the issue!

Benjamin

**Comment by Ralpharoo** [comment]
Just tested and the update is working perfectly. Thanks @TroubleMakerBen
